# A pretty simple script to find all the replication connections which aren't auto generated and convert them back to auto generated.
#
# Requires the Active Directory component of RSAT to be installed.
#

# Import the ActiveDirectory module
Import-Module -Name ActiveDirectory

# Get all replication links which aren't auto generated and change their options value to 1 (auto generated).
Get-ADReplicationConnection -Filter {AutoGenerated -eq $false} -Properties AutoGenerated,options | Set-ADReplicationConnection -Replace @{'options' = 1}
